package boundaries;

import daos.Globale;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author quent
 */
public class JIFPaysSupp extends javax.swing.JInternalFrame {

    private Connection icnx;
    private DefaultComboBoxModel idbcm;
    private Map<String, String> mapPays;

    /**
     * Creates new form JIFPaysSupp
     */
    public JIFPaysSupp() {
        initComponents();
        setVisible(true);
        icnx = Globale.getCnx();
        Statement lstSQL;
        ResultSet lrs;
        String lsSelect;

        // Bloc TRY and CATCH pour la requête SQL
        try {

            lsSelect = "SELECT id_pays, nom_pays FROM pays ORDER BY 2";
            lstSQL = icnx.createStatement();
            lrs = lstSQL.executeQuery(lsSelect);

            mapPays = new HashMap();
            
            idbcm = new DefaultComboBoxModel();
            while (lrs.next()) {
                idbcm.addElement(lrs.getString(2));
                mapPays.put(lrs.getString("nom_pays"), lrs.getString("id_pays"));
            }
            jComboBoxPaysDelete.setModel(idbcm);

            lrs.close();
            lstSQL.close();

            jLabelMessage.setText("Message");

        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }

    } /// Constructeur

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDelete = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jLabelPaysNomDelete = new javax.swing.JLabel();
        jComboBoxPaysDelete = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Suppresion pays");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jButtonDelete.setText("Supprimer");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabelMessage.setText("Message");

        jLabelPaysNomDelete.setText("Pays à supprimer?");

        jComboBoxPaysDelete.setEditable(true);
        jComboBoxPaysDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaysDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPaysNomDelete)
                        .addGap(36, 36, 36)
                        .addComponent(jComboBoxPaysDelete, 0, 115, Short.MAX_VALUE))
                    .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPaysNomDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPaysDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonDelete)
                .addGap(31, 31, 31)
                .addComponent(jLabelMessage)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        
        // Bloc TRY and CATCH pour la requête SQL
        try {
            // ORDRE SQL SUPPRESSION
            String lsSQL = "DELETE FROM pays WHERE id_pays = ?";

            // Création de l'objet "commande SQL"
            PreparedStatement lpst = icnx.prepareStatement(lsSQL);
            
            String lsNom = jComboBoxPaysDelete.getSelectedItem().toString();
            String lsId = mapPays.get(lsNom);
            
            // Valorisation du ou des paramètre(s)
            lpst.setString(1, lsId);
            // Exécution de la requête SQL
            lpst.executeUpdate();
            // Fermeture du curseur
            lpst.close();
            jLabelMessage.setText("Le pays " + jComboBoxPaysDelete.getSelectedItem() + " a bien été supprimé de la liste");
            // Pour la mise à jour automatique de liste suite à la suppression
            idbcm.removeElement(jComboBoxPaysDelete.getSelectedItem().toString());
            
        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jComboBoxPaysDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaysDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPaysDeleteActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
         // DECONNEXION DE LA BD
        try {
            icnx.close();
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JComboBox jComboBoxPaysDelete;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelPaysNomDelete;
    // End of variables declaration//GEN-END:variables
}
