package boundaries;

import java.sql.*;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author quent
 */
public class JIFPaysModif extends javax.swing.JInternalFrame {

    private Connection icn;
    private DefaultComboBoxModel idbcm;
    private Map<String, String> mapPays;

    /**
     * Creates new form JIFPaysModif
     */
    public JIFPaysModif() {
        initComponents();
        setVisible(true);
        
        Statement lstSQL;
        ResultSet lrs;
        String lsDSN;
        String lsSelect;

        try {
            lsDSN = "jdbc:mysql://127.0.0.1:3306/cinescope2017";
            icn = DriverManager.getConnection(lsDSN, "root", "");

            lsSelect = "SELECT NOM_pays FROM pays ORDER BY 1";
            lstSQL = icn.createStatement();
            lrs = lstSQL.executeQuery(lsSelect);

            idbcm = new DefaultComboBoxModel();
            while (lrs.next()) {
                idbcm.addElement(lrs.getString(1));
            }
            jComboBoxPaysModif.setModel(idbcm);

            lrs.close();
            lstSQL.close();

            jLabelMessage.setText("Message");

        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPays = new javax.swing.JTextField();
        jTextFieldMasculin = new javax.swing.JTextField();
        jTextFieldFeminin = new javax.swing.JTextField();
        jTextFieldNeutre = new javax.swing.JTextField();
        jButtonValiderModification = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxPaysModif = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modification pays");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pays à modifier?");

        jLabel2.setText("ID Pays");

        jTextFieldId.setEditable(false);
        jTextFieldId.setBackground(new java.awt.Color(255, 0, 0));
        jTextFieldId.setBorder(null);

        jLabel3.setText("Nom du pays");

        jLabel4.setText("Masculin");

        jLabel5.setText("Féminin");

        jTextFieldNeutre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNeutreActionPerformed(evt);
            }
        });

        jButtonValiderModification.setText("Valider Modification");
        jButtonValiderModification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderModificationActionPerformed(evt);
            }
        });

        jLabelMessage.setText("Message");

        jLabel8.setText("Neutre");

        jComboBoxPaysModif.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPaysModifItemStateChanged(evt);
            }
        });
        jComboBoxPaysModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaysModifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButtonValiderModification, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxPaysModif, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMasculin, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPays, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFeminin, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNeutre, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPaysModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldMasculin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldFeminin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNeutre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jButtonValiderModification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPaysModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaysModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPaysModifActionPerformed

    private void jTextFieldNeutreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNeutreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNeutreActionPerformed

    private void jComboBoxPaysModifItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPaysModifItemStateChanged
        
        PreparedStatement lpst;
        ResultSet lrs;

        try {
            
            String lsSelectOne = "SELECT * FROM pays WHERE NOM_pays = ?";
            
            // PreparedStatement permettant l'exécution de l'ordre SQL paramétré ci-dessus
            lpst = icn.prepareStatement(lsSelectOne);
            // Valorisation des paramètres de la requêt
            lpst.setString(1, jComboBoxPaysModif.getSelectedItem().toString());
            // Exécution de l'ordre SQL SELECT
            lrs = lpst.executeQuery();
            if (lrs.next()) {
                jTextFieldId.setText(lrs.getString(1));
                jTextFieldPays.setText(lrs.getString(2));
                jTextFieldMasculin.setText(lrs.getString(3));
                jTextFieldFeminin.setText(lrs.getString(4));
                jTextFieldNeutre.setText(lrs.getString(5));
            }else{
                jLabelMessage.setText("Un problème est survenu lors de la mise à jour.");
            }

            lrs.close();
            lpst.close();

        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jComboBoxPaysModifItemStateChanged

    private void jButtonValiderModificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderModificationActionPerformed

        // Déclaration des variables et récupération des infos inscrites dans les différents champs
        PreparedStatement lpst;
        String lsUpdate = "UPDATE pays SET nom_pays = ?, masculin = ?, feminin = ?, neutre = ? WHERE id_pays = ?";;
        String lsNomPays = jTextFieldPays.getText().toString();
        String lsMasculin = jTextFieldMasculin.getText().toString();
        String lsFeminin = jTextFieldFeminin.getText().toString();
        String lsNeutre = jTextFieldNeutre.getText().toString();
        String lsId = jTextFieldId.getText().toString();

        // Bloc TRY and CATCH
        try {
            // PreparedStatement permettant l'exécution de l'ordre SQL paramétré
            lpst = icn.prepareStatement(lsUpdate);

            // Valorisation des paramètres de la requête
            lpst.setString(1, lsNomPays);
            lpst.setString(2, lsMasculin);
            lpst.setString(3, lsFeminin);
            lpst.setString(4, lsNeutre);
            lpst.setString(5, lsId);

            // Exécution de la requête
            lpst.executeUpdate();

            // Fermeture du curseur
            lpst.close();
            jLabelMessage.setText("Le pays " + jComboBoxPaysModif.getSelectedItem() + " a bien été modifé.");

            // Bloc CATCH si une erreur a été levée
        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonValiderModificationActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

        // DECONNEXION DE LA BD
        try {
            icn.close();
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValiderModification;
    private javax.swing.JComboBox jComboBoxPaysModif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JTextField jTextFieldFeminin;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldMasculin;
    private javax.swing.JTextField jTextFieldNeutre;
    private javax.swing.JTextField jTextFieldPays;
    // End of variables declaration//GEN-END:variables
}
