// Package dans lequel on se trouve
package boundaries;

// Importation des bibliothèques Entrées/Sorties
import java.sql.*;

/**
 *
 * @author quent
 */
public class JIFPaysAjout extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFPaysAjout
     */
    public JIFPaysAjout() {
        // Initialisation des composants de la JInternalFrame
        initComponents();
        // Rendre visible la fenêtre
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldPays = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMasculin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFeminin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNeutre = new javax.swing.JTextField();
        jButtonAjoutPays = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ajout pays");

        jLabel1.setText("Nom du pays");

        jTextFieldPays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPaysActionPerformed(evt);
            }
        });

        jLabel2.setText("Masculin");

        jTextFieldMasculin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMasculinActionPerformed(evt);
            }
        });

        jLabel3.setText("Féminin");

        jTextFieldFeminin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFemininActionPerformed(evt);
            }
        });

        jLabel4.setText("Neutre");

        jTextFieldNeutre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNeutreActionPerformed(evt);
            }
        });

        jButtonAjoutPays.setText("Ajouter");
        jButtonAjoutPays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutPaysActionPerformed(evt);
            }
        });

        jLabelMessage.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAjoutPays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPays, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jTextFieldMasculin)
                            .addComponent(jTextFieldFeminin)
                            .addComponent(jTextFieldNeutre)))
                    .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMasculin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldFeminin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNeutre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButtonAjoutPays)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabelMessage)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMasculinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMasculinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMasculinActionPerformed

    private void jTextFieldFemininActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFemininActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFemininActionPerformed

    private void jTextFieldPaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPaysActionPerformed

    private void jTextFieldNeutreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNeutreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNeutreActionPerformed

    // Procédure pour le bouton de validation
    private void jButtonAjoutPaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutPaysActionPerformed

        // Déclaration des variables et récupération des infos inscrites dans les différents champs
        String lsPays = jTextFieldPays.getText();
        String lsMasculin = jTextFieldMasculin.getText();
        String lsFeminin = jTextFieldFeminin.getText();
        String lsNeutre = jTextFieldNeutre.getText();

        /*
         * Condition afin de pouvoir entrer dans le bloc Try and Catch:
         * Si un champs des champs du formulaire est vide, alors on affiche le 
         * message "Tout les champs sont obligatoires."
         */
        if (lsPays.isEmpty() || lsMasculin.isEmpty() || lsFeminin.isEmpty() || lsNeutre.isEmpty()) {
            jLabelMessage.setText("Tout les champs sont obligatoires.");
            // Sinon
        } else {
            // Début du bloc Try
            try {
                // Méthode pour la connexion à la DB
                String lsDSN;
                lsDSN = "jdbc:mysql://127.0.0.1:3306/cinescope2017";
                Connection lcn = DriverManager.getConnection(lsDSN, "root", "");

                // Requête prépaprée pour l'insertion d'un nouveau pays dans la table pays
                String lstSQL = "INSERT INTO pays (NOM_pays, MASCULIN, FEMININ, NEUTRE) VALUES(?,?,?,?)";
                // PreparedStatement permettant l'exécution de l'ordre SQL paramétré ci-dessus 
                PreparedStatement lpst = lcn.prepareStatement(lstSQL);

                /*
                 * Valorisation des différents paramètres de l'ordre SQL INSERT.
                 * Chaques valeurs des ? correpondent aux paramètres de l'ordre SQL.
                 */
                lpst.setString(1, jTextFieldPays.getText());
                lpst.setString(2, jTextFieldMasculin.getText());
                lpst.setString(3, jTextFieldFeminin.getText());
                lpst.setString(4, jTextFieldNeutre.getText());

                // Exécution de l'ordre SQL INSERT
                int liAffecte = lpst.executeUpdate();

                // Si l'ordre a bien été exécuté, affichage d'un message de réussite
                if (liAffecte == 1) {
                    jLabelMessage.setText("Le pays " + jTextFieldPays.getText() + " et ses informations ont bien été aujoutés.");
                    // Sinon affiche comme quoi il y a eu un incident
                } else {
                    jLabelMessage.setText("Erreur dans l'insertion.");
                }
                // Fermeture du curseur
                lpst.close();
                // Déconnexion de la BD
                lcn.close();
            }// Fin du TRY
            // Bloc CATCH si une erreur a été levée
            catch (SQLException ex) {
                // Affichage de l'erreur à l'endroit voulu dans la fenêtre
                jLabelMessage.setText(ex.getMessage());
            }// Fin du CATCH
        }// Fin du premier else
    }//GEN-LAST:event_jButtonAjoutPaysActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjoutPays;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JTextField jTextFieldFeminin;
    private javax.swing.JTextField jTextFieldMasculin;
    private javax.swing.JTextField jTextFieldNeutre;
    private javax.swing.JTextField jTextFieldPays;
    // End of variables declaration//GEN-END:variables
}
