package boundaries;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quent
 */
public class JIFPaysVisu extends javax.swing.JInternalFrame {

    private Connection icn;

    /**
     * Creates new form JIFPaysVisu
     */
    public JIFPaysVisu() {
        initComponents();
        setVisible(true);

        PreparedStatement lpst;
        ResultSet lrs;
        String lsDSN;
        Object[] tEntetes;
        Object[][] tDataTable;
        Object[] tDataLigne;

        try {
            // Connexion à la DB
            lsDSN = "jdbc:mysql://127.0.0.1:3306/cinescope2017";
            icn = DriverManager.getConnection(lsDSN, "root", "");

            lpst = icn.prepareStatement("SELECT * FROM pays");
            lrs = lpst.executeQuery();

            /*
             * Récupération de la structure du curseur
             * Le tableau d'Objet des en-têtes est rempli à partir des noms des 
             * colonnes du curseur grâce au ResultSetMetaData.
             */
            ResultSetMetaData lrsmd = lrs.getMetaData();
            // Nombre de colonnes du curseur
            int liColonnes = lrsmd.getColumnCount();
            // Noms des colonnes de la table
            tEntetes = new Object[liColonnes];
            for (int i = 0; i < liColonnes; i++) {
                tEntetes[i] = lrsmd.getColumnName(i + 1);
            }

            /* 
             * Pour l'insertion des données de la table dans la jTablePays
             * Pour obtenir le nombre d'enregistrements et pouvoir dimensionner le tableau,
             * il faut se positionner sur le dernier enregistrement.
             */
            lrs.last();
            int liLignes = lrs.getRow();
            tDataTable = new Object[liLignes][liColonnes];

            lrs.beforeFirst();
            int i = 0;
            // Balayage des lignes
            while (lrs.next()) {
                // Balayage des colonnes pour construire une ligne
                tDataLigne = new Object[liColonnes];
                for (int j = 0; j < liColonnes; j++) {
                    if (lrs.getObject(j + 1) == null) {
                        tDataLigne[j] = "NUL";
                    } else {
                        tDataLigne[j] = lrs.getObject(j + 1).toString();
                    }
                }
                tDataTable[i] = tDataLigne;
                i++;
            }

            // La jTablePays est remplie avec les deux tableaux créés
            jTablePays.setModel(new DefaultTableModel(tDataTable, tEntetes));

            // Fermetures
            lrs.close();
            lpst.close();
            

        } catch (SQLException e) {
            jLabelMessage.setText(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePays = new javax.swing.JTable();
        jLabelMessage = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Visu pays");

        jTablePays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablePays.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTablePays);

        jLabelMessage.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jLabelMessage)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePays;
    // End of variables declaration//GEN-END:variables
}
